[package]
name = "hello_world"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
keywords = ["observability", "metrics", "example"]

[dependencies]
enya.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
