[build]
rustflags = ["--cfg", "tokio_unstable"]

# Use mold linking for linux builds
[target.'cfg(target_os = "linux")']
rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=mold"]

# Configure getrandom to use JS backend for WASM builds
[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "getrandom_backend=\"wasm_js\""]
