[package]
name = "enya-build-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
description = "Build tools for enya crates"
license.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
keywords = ["build", "tools"]

[dependencies]
cargo_metadata = "0.18"

[lints]
workspace = true
