[package]
name = "enya-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
egui = { workspace = true }
eframe = { workspace = true, default-features = false, features = [
  "default_fonts",
  "glow",
  "persistence",
] }
egui_extras = { workspace = true, features = ["image", "svg"] }
egui-phosphor = { workspace = true, features = ["thin"] }
egui_tiles = { workspace = true, features = ["serde"] }
egui_plot = { workspace = true }
smallvec = { workspace = true }
enya-lang = { workspace = true }
image = { workspace = true, features = ["png"] }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
base64 = { workspace = true }
lz4_flex = "0.11"
postcard = { version = "1.1", features = ["alloc"] }
enya-build-info = { path = "../build-info" }
strum_macros = { workspace = true }
strum = { workspace = true }
nucleo-matcher = { workspace = true }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
parking_lot = { workspace = true, features = ["serde"] }
ewebsock = { workspace = true, features = ["tls"] }
env_logger = { workspace = true }
mimalloc = { workspace = true }
rustls = { workspace = true, features = ["ring"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
ewebsock = { workspace = true }
parking_lot = { workspace = true, features = ["wasm-bindgen", "serde"] }
wasm-bindgen-futures = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
  "Blob",
  "BlobPropertyBag",
  "Clipboard",
  "Document",
  "HtmlAnchorElement",
  "Location",
  "Navigator",
  "Url",
  "Window",
] }
web-time = { workspace = true }
gloo-timers = { workspace = true, features = ["futures"] }

[build-dependencies]
enya-build-tools = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
