name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  just:
    strategy:
      fail-fast: false
      matrix:
        target: [check-fmt, clippy, machete, test, deny]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: ./.github/actions/setup-rust

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-${{ matrix.target }}"
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Set up Just Runner
        uses: extractions/setup-just@v2

      - name: Run +${{ matrix.target }}
        run: just features=all ${{ matrix.target }}
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"


  check_wasm:
    name: Check wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: ./.github/actions/setup-rust

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "wasm32"
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check wasm32
        run: cargo check -p enya-editor --target wasm32-unknown-unknown --profile ci
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"
