[package]
name = "egui_nerdfonts"
description = "Nerdfonts icons for egui"
version = "0.1.7"
edition.workspace = true
readme = "README.md"
# Vendored from https://github.com/bernsteining/egui_nerdfonts
# Updated for egui 0.33
license = "MIT"
repository = "https://github.com/meldrumlabs/enya"

[dependencies]
egui = { workspace = true }

[lints]
workspace = true
